### ISSUE TITLE
Votes for Enable / Disable options for NexT website.

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/theme-next.org#1]
Here is current configuration file for main site: 
https://github.com/theme-next/theme-next.org/blob/source/_config.yml

Any settings can be on or off.
So, please, make a suggests with votes to them.

- [ ] `motion.enable` – http://www.easypolls.net/poll.html?p=5c0e9634e4b02fc1e449efe8

**Comment by sli1989** [comment]
choose `no`, as simple as possible.
