### ISSUE TITLE
How about use netlify

### ISSUE THREAD

**Issue by jiangtj** [theme-next/theme-next.org#12]
I saw netlify support deploy PR and preview it.
It's useful for docs previews.

https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/

How about use it?

**Comment by ivan-nginx** [comment]
Yeah, we can try it!
Can u try to create separated repo for test it before?

**Comment by jiangtj** [comment]
such as: https://github.com/JiangTJ/theme-next.org/pull/2
Some config in netlify:
![image](https://user-images.githubusercontent.com/15902347/50874414-e4a2b480-13fe-11e9-9b05-7aad4147c7aa.png)

**Comment by ivan-nginx** [comment]
Yeah, seems nice!

> Can u try to create separated repo for test it before?

Separated branch here i mean...

**Comment by ivan-nginx** [comment]
Done.

**Comment by jiangtj** [comment]
@ivan-nginx Sorry, Netlify has 100GB of bandwidth per month limited since 2019-2-26.
https://www.netlify.com/blog/2019/02/26/netlify-and-bandwidth/
It's enough for me, but I don't know if same in NexT.
If not, maybe we only use it to preview PR.

**Comment by ivan-nginx** [comment]
I think that's enough for NexT too.
From 1st March autodeploy created (5b572d4d6a19edbb067a395c9024b8d9751bc0e6) I made a script with many commits, cleared the cache and the guys added a lot of documents, usage wasted about just ≈300 MB:
![image](https://user-images.githubusercontent.com/16944225/53886450-59215a80-4020-11e9-88e8-d4c4948f44fd.png)

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/55042152-9631a900-5030-11e9-9385-3b58f1acf4cc.png)

Thank's for suggest this service. This very easy to use and no bugs was detected. Amazing service.

**Comment by ivan-nginx** [comment]
@all-contributors add @JiangTJ for infra.
