### ISSUE TITLE
Suggestion to refactor theme-next.org source

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/theme-next.org#33]
As I feel, there is some troubles between switching from NexT source to NexT website source during adding Features or new Options. When we add some new Option, we must add docs for this options, so, we must to switch to another repo and make changes there.

I suggest to move [theme-next.org](https://github.com/theme-next/theme-next.org) repo (source branch) here, directly in [hexo-theme-next](https://github.com/theme-next/hexo-theme-next) repo under, for example, **theme-next.org** branch. This will provide easyier editing docs for NexT by just switching branches, and will be all in one.

But I'm not sure about it because if at an early date we can adapt NexT for Jekyll or for Hugo, then this move will unneded. As for me, there is no troubles between switching repositories and editing docs source there. But what are you thinking about that, guys?

**Comment by LEAFERx** [comment]
Move source/docs folder in theme-next.org to docs folder in hexo-theme-next and build every time when docs changes?

**Comment by ivan-nginx** [comment]
> Move source/docs folder in theme-next.org to docs folder in hexo-theme-next and build every time when docs changes?

I think there is no need, because `_post` and `docs` directory — are `*.md` files. 

***

Because total votes are 6 and all for 1st variant, we keep stay this repo without changes.
