### ISSUE TITLE
<li> contains <p>?

### ISSUE THREAD

**Issue by jiangtj** [theme-next/theme-next.org#38]
![image](https://user-images.githubusercontent.com/15902347/54904221-e4538900-4f18-11e9-9946-3063ea63b781.png)
#34 also has this issue.

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/54908309-e05b4300-4ee7-11e9-8bb1-fc2b7fc70be7.png)

**Comment by jiangtj** [comment]
!!!
I try this

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/54909012-27ffc000-4f24-11e9-8e80-f8cd949d3d4d.png)
4 space, normal in master....

**Comment by ivan-nginx** [comment]
Must be 3 spaces.

**Comment by jiangtj** [comment]
![image](https://user-images.githubusercontent.com/15902347/54969116-0819dc00-4fb8-11e9-93c0-d52f22812a2f.png)
@ivan-nginx It's not caused by this. 3 spaces same.

**Comment by ivan-nginx** [comment]
I tested it, all was fine.
Maybe u need to reinstall md renderer?
