### ISSUE TITLE
An error in the docs

### ISSUE THREAD

**Issue by chhlab** [theme-next/theme-next.org#45]
the error lies in docs → Third Party Services → Math Equations → 2. Render Engines → mathjax → Installation,  **"katex"** should be **"mathjax"**, [Link](https://theme-next.org/docs/third-party-services/math-equations) 

> In theme config file, turn on enable option of math and choose **_katex_** as render engine.
![image](https://user-images.githubusercontent.com/48938342/55322672-8c37fc00-54af-11e9-9b12-a090c9924a5c.png)

**Comment by 1v9** [comment]
Thanks, we will fix it.

**Comment by ivan-nginx** [comment]
Fixed.
