### ISSUE TITLE
note-icon not display

### ISSUE THREAD

**Issue by linchunbogit** [theme-next/theme-next.org#51]
$note-warning-icon          = "\f06a"

any of note icon can not display on my blog

**Comment by jiangtj** [comment]
I don't know what you said, Can you provide more info?

**Comment by linchunbogit** [comment]
thanks !
here img, top is mine and bom is you, and the red frame tip is what i want
![20190429154341](https://user-images.githubusercontent.com/39016620/56882420-1c109c00-6a96-11e9-94ca-c90e5c88f32f.jpg)

**Comment by jiangtj** [comment]
You have to set icons to `true`
https://github.com/theme-next/hexo-theme-next/blob/c7689deb4c1765c9b0222fdb807e22ee2e80d086/_config.yml#L903-L914

<blockquote><img src="https://avatars3.githubusercontent.com/u/32585093?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/theme-next/hexo-theme-next">theme-next/hexo-theme-next</a></strong></div><div>Elegant and powerful theme for Hexo. Contribute to theme-next/hexo-theme-next development by creating an account on GitHub.</div></blockquote>

**Comment by linchunbogit** [comment]
oh !  thanks +++++++
i set true and it work perfect!
