### ISSUE TITLE
404 page not work

### ISSUE THREAD

**Issue by linchunbogit** [theme-next/theme-next.org#52]
i make the new 404 page, but it not work on i open the invalid post
where i can set the 404

**Comment by linchunbogit** [comment]
here mime blog , i make 2 404.md but not one world
![404](https://user-images.githubusercontent.com/39016620/56883730-23d23f80-6a9a-11e9-8132-36f16c05d82d.jpg)

**Comment by stevenjoezhang** [comment]
Is it `404/index.md` ?

**Comment by linchunbogit** [comment]
yes,
![4044](https://user-images.githubusercontent.com/39016620/56892452-39536380-6ab2-11e9-9f15-d2b84bf94e48.jpg)

**Comment by linchunbogit** [comment]
it can work on manual visit 404 page

![4043](https://user-images.githubusercontent.com/39016620/56892680-f776ed00-6ab2-11e9-8507-4eaca6adf0b1.jpg)

**Comment by stevenjoezhang** [comment]
Oh, you mean if you open an invalid post, the server won't redirect to `/404/index.html` ?

**Comment by linchunbogit** [comment]
yes，like this！
i want it open mine custom 404 page on post open fail

**Comment by online** [comment]
@linchunbogit, where do you host your blog? 404 page won't work on localhost.

**Comment by linchunbogit** [comment]
it work on munual open url
http://www.blog.6bianshi.com/404/

<blockquote><div><img src="/images/favicon.png?v=7.1.0" height="14"> popo</div><div><strong><a href="http://yoursite.com/404/index.html">404</a></strong></div><div>123456789101112131415404    not        found            4444      4444    0000000000    4444      4444            4444      4444  00000000000000  4444      4444            4444      4444  0000      00</div></blockquote>

**Comment by online** [comment]
https://help.github.com/en/articles/creating-a-custom-404-page-for-your-github-pages-site

<blockquote><div><strong><a href="https://help.github.com/en/articles/creating-a-custom-404-page-for-your-github-pages-site">Creating a custom 404 page for your GitHub Pages site - GitHub Help</a></strong></div></blockquote>

**Comment by linchunbogit** [comment]
i use hexo not github page

**Comment by jiangtj** [comment]
> i use hexo not github page

Hexo is a util to generate website, not deploy environment. Can you give where you deploy?

There are different configuration in per deploy environment.

**Comment by stevenjoezhang** [comment]
Yes, for example, if you are using Nginx, you need to edit `nginx.conf` to set the 404 page
