### ISSUE TITLE
> 建议在说明文档内添加一个变更说明，不然升级变更了都无从下手了，谢谢

### ISSUE THREAD

**Issue by 1v9** [theme-next/theme-next.org#66]
> 建议在说明文档内添加一个变更说明，不然升级变更了都无从下手了，谢谢

https://github.com/theme-next/hexo-theme-next/releases
https://theme-next.org/

<blockquote><img src="https://avatars3.githubusercontent.com/u/32585093?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/theme-next/hexo-theme-next">theme-next/hexo-theme-next</a></strong></div><div>Elegant and powerful theme for Hexo. Contribute to theme-next/hexo-theme-next development by creating an account on GitHub.</div></blockquote>
<blockquote><div><img src="/images/favicon-16x16-next.png?v=7.2.0" height="14"> NexT</div><div><strong><a href="https://theme-next.org/index.html">NexT</a></strong></div></blockquote>

_Originally posted by @stevenjoezhang in https://github.com/theme-next/hexo-theme-next/issues/982#issuecomment-512897584_

**Comment by stevenjoezhang** [comment]
意思是已经添加了...

**Comment by 1v9** [comment]
@stevenjoezhang Where?

**Comment by stevenjoezhang** [comment]
点开这两个链接，都是变更说明啊...

**Comment by 1v9** [comment]
@stevenjoezhang 所以应该提示用户优先按 tag/release 使用主题，master 分支等于开发分支 🤷‍♂️

**Comment by stevenjoezhang** [comment]
我看下别的主题是怎么做的

**Comment by jiangtj** [comment]
https://github.com/theme-next/hexo-theme-next/issues/567
看这个，master 分支作为开发分支 是一种 比较好的实践
