### ISSUE TITLE
External links on the website doesn't work as expected

### ISSUE THREAD

**Issue by maple3142** [theme-next/theme-next.org#74]
When I try to middle click any external link on the website, it won't open in newtab like regular link, which is really bad for UX.
What's more, it opens a **window** instead of newtab when I left click on it.
Video: https://streamable.com/w5lwa

**Comment by 1v9** [comment]
Why do I have a wheel present instead of opening a new window after middle clicking any external link?

**Comment by 1v9** [comment]
Left click is normal, open a new tab.

**Comment by liolok** [comment]
Shouldn't that link be opened in a new window? It's an authorization page after all. I guess it's expected behavior. :3

**Comment by maple3142** [comment]
@liolok IMO, I don't think it is good to override the normal behavior of links, because it will break a lot of things such as middle click to open in new tab.

**Comment by stevenjoezhang** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

**Comment by maple3142** [comment]
@stevenjoezhang What do you mean in this link? I am not using Edge.

**Comment by stevenjoezhang** [comment]
According to the investigation of several members, this issue is related to the behavior of the mouse driver program and the browser. The bug is reproduced only on edge browser, while the firefox and webkit based browsers are working as expected.

**Comment by maple3142** [comment]
But I am using CentBrowser, which is based on Chromium.

**Comment by 1v9** [comment]
@maple3142 It's CnetBrowser's fault, even Edge Chromium is normal as Chrome.

**Comment by maple3142** [comment]
@1v9 I know that `window.open` only not working correctly in CentBrowser, but middle click to open in new tab works nowhere(Chrome, Firefox...)

**Comment by 1v9** [comment]
@maple3142 In fact, we didn't meet this issue. Middle click ------> a wheel, Firefox & Chrome is same. There's not a new tab or window open.

**Comment by 1v9** [comment]
Maybe try another computer(

**Comment by maple3142** [comment]
@1v9 You can middle click on any normal `<a>` link on a fresh installed Chrome or Firefox and see what happens.
Chrome: https://streamable.com/mvpnc
Firefox: https://streamable.com/hl662

**Comment by 1v9** [comment]
@maple3142 Are you in our tele group? My english is bad(

**Comment by maple3142** [comment]
What's about making **exturl** to be a simple `<a>` like this:
`<a href="..." rel="noopener">...</a>`

**Comment by ivan-nginx** [comment]
I don't think what we can change <span> to <a> to external links because SEO issues.
I think we can just add middle click action via JS in `exturl` script?
About new window → it's CentBrowser bug, on all other browsers new tab opened always.
