### ISSUE TITLE
script not working well！

### ISSUE THREAD

**Issue by yifengyou** [theme-next/theme-next.org#80]
`curl -L https://api.github.com/repos/hexojs/hexo-starter/tarball | tar -zxv -C ./ --strip-components=1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   258  100   258    0     0     15      0  0:00:17  0:00:16  0:00:01    68

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

**Comment by stevenjoezhang** [comment]
Can't reproduce.
```
Mac:~ Mimi$ curl -L https://api.github.com/repos/hexojs/hexo-starter/tarball | tar -zxv -C ./ --strip-components=1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2068    0  2068    0     0   1479      0 --:--:--  0:00:01 --:--:-- 1333k
x .gitignore
x .gitmodules
x _config.yml
x package.json
x scaffolds/
x scaffolds/draft.md
x scaffolds/page.md
x scaffolds/post.md
x source/
x source/_posts/
x source/_posts/hello-world.md
x themes/
x themes/landscape/
```

**Comment by stevenjoezhang** [comment]
Script updated https://github.com/theme-next/theme-next.org/commit/39410dcff4c9f963a9f2d2712b8fdc8bfd217572
