### ISSUE TITLE
theme-next.org is currently down

### ISSUE THREAD

**Issue by hifocus** [theme-next/theme-next.org#92]
![image](https://user-images.githubusercontent.com/30528433/81463099-7f74f400-91e9-11ea-9346-168907c7da5f.png)

![image](https://user-images.githubusercontent.com/30528433/81463104-86036b80-91e9-11ea-96b6-d4ce170db82f.png)

Please see if any fixes is needed.

**Comment by sli1989** [comment]
Thanks. noted.
because of the technical issue, ths site is unreachable for now. be patient.
for help, u may look into the files in repo.

**Comment by sli1989** [comment]
temp access: https://hexo-theme-next.netlify.app/

<blockquote><div><img src="/images/favicon-16x16-next.png" height="14"> NexT</div><div><strong><a href="https://theme-next.js.org/index.html">NexT</a></strong></div></blockquote>
